---
- name: import key
  rpm_key:
    state: present
    key: https://packages.microsoft.com/keys/microsoft.asc

- name: add repo
  copy:
    src: vscode.repo
    dest: /etc/yum.repos.d/

- name: install vscode
  yum:
    name: code
    state: present